language: php

php:
  - 5.3
  - 5.4
  - 5.5

script: find . -type f -name *.php | xargs -n1 php -l 

deploy:
  provider: heroku
  app:
    master: rocros
    develop: rocros-dev
  api_key: 
    secure: "FjxMtOL3cmtMkBGn80t6xeKQiQvtxZGssSTqm161ARzagNrLjfeDmd03z/tM13/pC8sV4HU9iCiNRJs5wYLsrCR1HC2MzEqOH0rgwaQ0KO9YsiCroPIEJhTKK+kRv0wVtzZBJ6uLkK2fVZJreakBoT6PGSQxkUJpre4q8EUDfg4="
  on:
    php: 5.5

notifications:
  hipchat:
    rooms:
      secure: "RmSeVdLBznAniVILhdvzG/2PDJBBw5jGRzqkGebyq/aOHqJm2oitImO0ywoem/ldMnW9UhwiNC/tnO+6nMGVpb/RRhOBcudiCA4C2LMq/M10GN5+3i+PFRu4VHqWGaiC/TVXtewMjfx2kqffFe4nVADQXk8H37nMCjIU+TqRRo8="
